# Generated by Django 5.2.5 on 2025-08-21 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='grad',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='destination',
            name='drzava',
            field=models.CharField(default='Hrvatska', max_length=100),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=160)),
                ('tip', models.CharField(choices=[('HOTEL', 'Hotel'), ('APARTMAN', 'Apartman'), ('HOSTEL', 'Hostel'), ('VILA', 'Vila')], max_length=20)),
                ('kapacitet_jedinica', models.PositiveIntegerField(default=1, help_text='Broj istovjetnih jedinica (npr. 5 soba).')),
                ('cijena_po_nocenju', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smjestaji', to='reservations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('broj_osoba', models.PositiveIntegerField(default=1)),
                ('ukupna_cijena', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smjestaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_bookings', to='reservations.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smjestaj_rezervacije', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_polaska', models.DateField()),
                ('cijena_osnovno', models.DecimalField(decimal_places=2, help_text='Osnovna cijena aranžmana po osobi.', max_digits=10)),
                ('cijena_prijevoza', models.DecimalField(decimal_places=2, help_text='Cijena organiziranog prijevoza po osobi.', max_digits=10)),
                ('broj_mjesta', models.PositiveIntegerField(default=50)),
                ('destinacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponude_putovanja', to='reservations.destination')),
            ],
            options={
                'ordering': ['datum_polaska'],
                'unique_together': {('destinacija', 'datum_polaska')},
            },
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prijevoz', models.CharField(choices=[('ORGANIZIRANO', 'Organizirani prijevoz (naš)'), ('OSOBNO', 'Osobno vozilo')], default='ORGANIZIRANO', max_length=20)),
                ('broj_osoba', models.PositiveIntegerField(default=1)),
                ('ukupna_cijena', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putovanje_rezervacije', to=settings.AUTH_USER_MODEL)),
                ('ponuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to='reservations.tripoffer')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
