# Generated by Django 5.2.5 on 2025-08-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_name_destination_grad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='grad',
            new_name='naziv',
        ),
    ]
