# Generated by Django 5.2.5 on 2025-08-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_grad_destination_naziv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='prijevoz',
            field=models.CharField(choices=[('osobno', 'Osobno vozilo'), ('organizirano', 'Organizirani prijevoz (naš)')], default='organizirano', max_length=20),
        ),
    ]
