# Generated by Django 5.2.5 on 2025-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_tripbooking_prijevoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='prijevoz',
            field=models.CharField(choices=[('ORGANIZIRANO', 'Organizirani prijevoz (naše vozilo)'), ('OSOBNO', 'Osobno vozilo')], default='ORGANIZIRANO', max_length=20),
        ),
    ]
