# Generated by Django 5.2.5 on 2025-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_tripbooking_prijevoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbooking',
            name='prijevoz',
            field=models.CharField(choices=[('NASE', 'Naše vozilo'), ('OSOBNO', 'Osobno vozilo')], default='NASE', max_length=20),
        ),
    ]
