# Generated by Django 5.2.5 on 2025-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_tripbooking_prijevoz'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='zvjezdice',
            field=models.PositiveIntegerField(default=3, help_text='Broj zvjezdica (1-5)'),
        ),
    ]
