# Generated by Django 5.2.5 on 2025-09-01 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_accommodation_zvjezdice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripoffer',
            name='cijena_prijevoza',
        ),
        migrations.CreateModel(
            name='TripTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_vozila', models.CharField(choices=[('AUTOBUS', 'Autobus'), ('VLAK', 'Vlak'), ('AVION', 'Avion'), ('AUTOMOBIL', 'Automobil')], max_length=20)),
                ('cijena_po_osobi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broj_mjesta', models.PositiveIntegerField(default=50)),
                ('ponuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijevozi', to='reservations.tripoffer')),
            ],
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='prijevoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to='reservations.triptransport'),
        ),
    ]
