# Generated by Django 5.1.3 on 2024-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_destination_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
