# Generated by Django 5.2.5 on 2025-09-01 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_remove_tripoffer_cijena_prijevoza_triptransport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triptransport',
            old_name='broj_mjesta',
            new_name='max_mjesta',
        ),
        migrations.RenameField(
            model_name='triptransport',
            old_name='tip_vozila',
            new_name='vozilo',
        ),
        migrations.RemoveField(
            model_name='triptransport',
            name='cijena_po_osobi',
        ),
        migrations.AddField(
            model_name='triptransport',
            name='cijena',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='kapacitet_jedinica',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='zvjezdice',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tripbooking',
            name='prijevoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.triptransport'),
        ),
    ]
