# Generated by Django 5.1.3 on 2024-12-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.destination'),
        ),
    ]
