# Generated by Django 5.2.5 on 2025-09-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_rename_broj_mjesta_triptransport_max_mjesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='triptransport',
            old_name='max_mjesta',
            new_name='max_osoba',
        ),
        migrations.RemoveField(
            model_name='triptransport',
            name='vozilo',
        ),
        migrations.AlterField(
            model_name='tripoffer',
            name='cijena_osnovno',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='triptransport',
            name='transport_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservations.transporttype'),
        ),
    ]
