# Generated by Django 5.2.5 on 2025-09-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_transporttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triptransport',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.transporttype'),
        ),
    ]
